### ISSUE TITLE
Some popup balloons are not fully visible

### ISSUE THREAD

**Issue by cbotsikas** [aegisbigdata/documentation#10]
In Jupyter page, on the right side there are three buttons, hovering them, there is a popup but it's not always visible.

![project_jupyter01](https://user-images.githubusercontent.com/1640100/43765261-d0260bd6-9a2f-11e8-8450-cb40f4bc38e5.PNG)

**Comment by AleCalcagno** [comment]
Fixed (to be deployed on the TESTBED)
