### ISSUE TITLE
Login and Register Page

### ISSUE THREAD

**Issue by FabiApfelkern** [aegisbigdata/documentation#105]
![image](https://user-images.githubusercontent.com/1488424/53889954-9b9a6580-4027-11e9-81bf-07dfa80170b4.png)
![image](https://user-images.githubusercontent.com/1488424/53890015-b7057080-4027-11e9-881f-7a9249dd4f23.png)

**Comment by Ambradibi** [comment]
I make it more homogeneous ok?

**Comment by FabiApfelkern** [comment]
Yes!

**Comment by Ambradibi** [comment]
![Schermata 2019-03-20 alle 14 38 26](https://user-images.githubusercontent.com/47423916/54688402-d9b28180-4b1d-11e9-9d0f-3af661109608.png)
Do you like it?

**Comment by FabiApfelkern** [comment]
Yes, but can we have the AEGIS blue instead of this grey?

**Comment by Ambradibi** [comment]
yes of course. But of all the elements?

**Comment by FabiApfelkern** [comment]
No just the header with the AEGIS logo
