### ISSUE TITLE
Add label to top buttons

### ISSUE THREAD

**Issue by Ambradibi** [aegisbigdata/documentation#106]
If they are three is acceptable (in my opinion).

![screen shot 2019-03-07 at 12 12 03](https://user-images.githubusercontent.com/47423916/53953592-043f1c00-40d4-11e9-8baa-3fb60aaa1deb.png)

But with so many buttons is not confusing? The seven extra buttons exit when clicking on a file. 

![screen shot 2019-03-07 at 12 14 19](https://user-images.githubusercontent.com/47423916/53953626-1456fb80-40d4-11e9-899f-e81614485bb9.png)

All on one line do not fit.

![screen shot 2019-03-07 at 12 16 37](https://user-images.githubusercontent.com/47423916/53953675-381a4180-40d4-11e9-9300-055ec245464a.png)

And with this design they are unwatchable, always in my opinion.

![screen shot 2019-03-07 at 12 19 37](https://user-images.githubusercontent.com/47423916/53953705-52541f80-40d4-11e9-8e3a-afb57f2d7b08.png)

I propose a dropdown, what do you think? Do you have any other ideas? (Moreover the buttons are divided into 3 groups depending on specific conditions)

![screen shot 2019-03-07 at 15 06 15](https://user-images.githubusercontent.com/47423916/53962307-ffd22d80-40ea-11e9-8242-b82b92da766e.png)

**Comment by smouzakitis** [comment]
How about a combination of the two (like some sites doe). Select 3-4 main (Parent folder,upload, download,  new folder) - and with less text in each label e.g. Download instead of download file and then More actions and the drop down list

**Comment by Ambradibi** [comment]
> How about a combination of the two (like some sites do). Select 3-4 main (Parent folder,upload, download, new folder) - and with less text in each label e.g. Download instead of download file and then More actions and the drop down list

Do you mean that?

![screen shot 2019-03-07 at 15 37 07](https://user-images.githubusercontent.com/47423916/53965941-6c9cf600-40f2-11e9-8c80-22fdf1334074.png)

And when you clicking on a file:

![screen shot 2019-03-07 at 15 52 56](https://user-images.githubusercontent.com/47423916/53965966-80e0f300-40f2-11e9-85d9-896a7c162365.png)

If we put the icons on the right? What do you think?

<img width="1464" alt="screen shot 2019-03-07 at 16 53 00" src="https://user-images.githubusercontent.com/47423916/53969745-9b6a9a80-40f9-11e9-99c4-95be053b6821.png">

**Comment by smouzakitis** [comment]
maybe yes, maybe we can make Go to parent directory smaller?

**Comment by Ambradibi** [comment]
> maybe yes, maybe we can make Go to parent directory smaller?

yes of course

**Comment by FabiApfelkern** [comment]
I like the idea with the more actions dropdown very much. May just call it "File Actions" or something like this.

**Comment by FabiApfelkern** [comment]
Yes rename "Go to parent directory" to "Go up"

**Comment by FabiApfelkern** [comment]
We talked in the telko about. Do it like this! :)
