### ISSUE TITLE
Home Page - Improve Icons

### ISSUE THREAD

**Issue by FabiApfelkern** [aegisbigdata/documentation#109]

**Comment by cbotsikas** [comment]
Change the Icons, Change the text and change the links of “Getting Started”, AEGIS marketplace (link to search), What’s New (link to site news) => maybe make them buttons?

**Comment by smouzakitis** [comment]
Text for under the buttons
Getting started
If you are new to AEGIS click here! Learn how to use the AEGIS tools through a quick tutorial
=>link as it is now to getting started

AEGIS Marketplace
See what's possible with AEGIS! Browse popular AEGIS datasets to use for your project
=>Link to the search page

What's New
Find out the latest news related to the AEGIS platform
=>https://www.aegis-bigdata.eu/news-events/

**Comment by smouzakitis** [comment]
Graphics:

[Icons.zip](https://github.com/aegisbigdata/documentation/files/3224272/Icons.zip)
![marketplace](https://user-images.githubusercontent.com/1720797/58428620-c090f880-80ab-11e9-9f02-20e9c4d55056.png)
![news](https://user-images.githubusercontent.com/1720797/58428624-c38be900-80ab-11e9-8ec8-ef64969fbaeb.png)
![getting_started](https://user-images.githubusercontent.com/1720797/58428627-c686d980-80ab-11e9-8502-0b50b48aac8a.png)
![preview](https://user-images.githubusercontent.com/1720797/58428623-c1c22580-80ab-11e9-830f-f9a1641e0177.png)

**Comment by cbotsikas** [comment]
@smouzakitis should i make the changes in code and commit?
