### ISSUE TITLE
Redesign Dataset Readme pane

### ISSUE THREAD

**Issue by Ambradibi** [aegisbigdata/documentation#121]
![Screen Shot 2019-03-12 at 17 12 58](https://user-images.githubusercontent.com/47423916/54218435-de5bb200-44ed-11e9-8ded-92ac1f6be784.png)

This is the current readme pane. I only changed the colors.
I asked Mahmoud if it was possible to change the size of the titles and the answer was: "yes, by updating the ReadMe file for that particular dataset, however, if you want to change it for every new dataset, we need to change the template in the backend. The current readme file is just a template generated by the backend whenever you add a dataset.".

So who could make the change to the readme? Or alternatively proposals on how to improve the appearance?

**Comment by smouzakitis** [comment]
Hi Ambra, i am not sure which task is related to this question?
we don't want to change the default information inside the README.md. This will be changed by the user of course. If for speicfic pages we want to change the appearance (e.g. for the demo review) we will do it manually

**Comment by Ambradibi** [comment]
I don't want to change the content but as shown (from the h1 tag to the h2 tag for example). What do you mean manually? 
sorry for the delay

**Comment by cbotsikas** [comment]
I don't understand what kind of change you want to do. These readme.md files are generated [using this template](https://github.com/aegisbigdata/hopsworks/blob/dev/hopsworks-common/src/main/java/io/hops/hopsworks/common/util/Settings.java#L1867-L1871) using markdown language.

I don't think we need to change the actual content.

**Comment by cbotsikas** [comment]
Nothing to do here.
