### ISSUE TITLE
Search page mockup

### ISSUE THREAD

**Issue by Ambradibi** [aegisbigdata/documentation#122]
![Screen Shot 2019-03-12 at 17 13 47](https://user-images.githubusercontent.com/47423916/54219034-f54ed400-44ee-11e9-93a4-44d35da93413.png)

Do you have comments about this graphic? Is information missing? Don't like the layout of the objects?
Based on the observations I can try to improve the appearance.

**Comment by smouzakitis** [comment]
Hi Ambra,

This was almost the same as the default of hopsworks. I see no changes other than sort by and type.
We said to change the layout look more like data gov portal sites for instance. Maybe all the filters are on a left column. Regarding the information we discussed in the meeting more info related to the metadata that FOKUS has in the metadata store, including e.g. license, spatial and temporal coverage

**Comment by Ambradibi** [comment]
<img width="1105" alt="Screen Shot 2019-03-13 at 10 38 34" src="https://user-images.githubusercontent.com/47423916/54268786-4c4eba80-457c-11e9-88d1-a955b30e608b.png">

so I put the forms (owner, name, etc.) on the left and dropdown (type and sort by) on the right? 
I don't understand if it's a problem to rearrange the elements or otherwise.

**Comment by smouzakitis** [comment]
It is both. We need new elements for fields not currently included in the hopsworks search (like license) . And i believe a new layout (like the ones in data gov) would be much better

**Comment by Ambradibi** [comment]
![Screen Shot 2019-03-13 at 15 44 36](https://user-images.githubusercontent.com/47423916/54287960-f17e8880-45a6-11e9-9558-ca5c2ac3e05c.png)

like this? Do you like it? the column of filter is fixed on the left (in this screen i've put only 3 filters)

**Comment by FabiApfelkern** [comment]
It's the right direction. I would propose to only have one result in a row and not two next to eachother.

**Comment by Ambradibi** [comment]
If you click on the button near 'X' you can see one result in a row. You can choose

**Comment by FabiApfelkern** [comment]
I would delete this options. Nobody needs it. Just have every dataset in one row. We decided on this anyways in Rome. :)

**Comment by Ambradibi** [comment]
![Schermata 2019-03-19 alle 10 30 34](https://user-images.githubusercontent.com/47423916/54594999-16a14a00-4a32-11e9-92db-5950c9834317.png)
![Schermata 2019-03-19 alle 10 30 45](https://user-images.githubusercontent.com/47423916/54595000-16a14a00-4a32-11e9-8c5e-55a8b99aea5a.png)


I know the license field is missing (@smouzakitis), but I don't know where to get it from.

**Comment by FabiApfelkern** [comment]
The licence field is not implemented yet. It will come.

**Comment by Ambradibi** [comment]
example? increase the font? reposition the elements to reduce white space?

**Comment by FabiApfelkern** [comment]
In my opinion the entire look of the box does not fit the AEGIS look. Yes, the font, too. The colored headlines. It's hard to tell.

**Comment by Ambradibi** [comment]
<img width="909" alt="Schermata 2019-03-19 alle 15 49 49" src="https://user-images.githubusercontent.com/47423916/54615620-b2e14600-4a5e-11e9-8c1f-b7a1723cb4a9.png">

- increased font
- changed color
- modal addition according to the styleguide
- reduced white spaces

any comments?

**Comment by FabiApfelkern** [comment]
- Type
  - Project
  - Dataset
  - Files
- Ownership
  - My Assets
  - Assets shared with me
  - No Access
- Date added to AEGIS
  - AS RANGE
- File Types
- Spatial
- Licence
- Prices / Sellable

**Comment by Ambradibi** [comment]
Thanks. I'll change today

**Comment by Ambradibi** [comment]
But what are the links?

**Comment by FabiApfelkern** [comment]
We don't have the links yet. Just mock it for now. :)
