### ISSUE TITLE
Files Page

### ISSUE THREAD

**Issue by Ambradibi** [aegisbigdata/documentation#125]
@ToDo Change colors to AEGIS colors. 

I don't understand where.

**Comment by FabiApfelkern** [comment]
It is like this:
![grafik](https://user-images.githubusercontent.com/1488424/55080148-e4c95c80-509d-11e9-84b5-081d97ef4dae.png)

But we want to have topbar like this:
![grafik](https://user-images.githubusercontent.com/1488424/55080186-fa3e8680-509d-11e9-9cac-97079c4894be.png)
