### ISSUE TITLE
Add menu point for Activity-Stream inside projects

### ISSUE THREAD

**Issue by cbotsikas** [aegisbigdata/documentation#132]
The activities stream has a dedicated url path `/project/:projectID/activities` as implemented [here](https://github.com/aegisbigdata/hopsworks/commit/7219b086a1de6ef3b2d9fa9d8efa56897f0baa65#diff-101d4349f9461330a05437c4c851c067R195).
At the moment it is not accessible by the users since there is no link to that page

**Comment by cbotsikas** [comment]
This is also relatef to https://github.com/aegisbigdata/documentation/issues/46 "Is the page with all the project activities listed needed?"

**Comment by Ambradibi** [comment]
![Schermata 2019-04-16 alle 15 56 38](https://user-images.githubusercontent.com/47423916/56215639-4313aa80-6060-11e9-8718-b999250df1e2.png)


I added the menu item and I left the 'ng-click' empty, right?
Moreover the icon is to be changed? If yes, in which one?

@cbotsikas

**Comment by cbotsikas** [comment]
Why empty? Create a new method like the goToDatasets, using the goToUrl for activities. For the icon, i don't know, improvise!
You could use `fa-list`, `fa-history` or `fa-clock-o` from fontawesome that we use or create a new png/svg. 
I've found a free one [from here](https://icons8.com/icon/13238/timeline) and modified it to match the rest of our icons being white: [icons8-timeline-48](https://user-images.githubusercontent.com/1640100/56234018-ae6f7380-6084-11e9-9285-4644b6e75f34.png)
You can use that if you want.

**Comment by Ambradibi** [comment]
ok, thanks! Merge request done
