### ISSUE TITLE
Dataset Page - Fix Breadcrumb, Clickable and add project name

### ISSUE THREAD

**Issue by cbotsikas** [aegisbigdata/documentation#133]

**Comment by cbotsikas** [comment]
related to https://github.com/aegisbigdata/documentation/issues/116

**Comment by Ambradibi** [comment]
![Schermata 2019-04-17 alle 11 40 05](https://user-images.githubusercontent.com/47423916/56277934-912eb980-6105-11e9-8213-5ba88bac2564.png)

I added the project name. Should it be clickable? if yes, which page should you link to?
