### ISSUE TITLE
Search Page - Add breadcrumb top bar

### ISSUE THREAD

**Issue by cbotsikas** [aegisbigdata/documentation#134]
I assume we need the breadcrumb when searching inside a project

**Comment by Ambradibi** [comment]
What breadcrumb? To return to the homepage? @cbotsikas

**Comment by cbotsikas** [comment]
Search is accessible inside project too, not only the main page. At the moment i can only find the search box in dateset view eg. https://bbc6.sics.se:8181/aegis/#!/project/3108/datasets/Experiments/
There should be a breadcrumb on this view. I don't think we need one from the main page search.

![image](https://user-images.githubusercontent.com/1640100/56248151-6b72c780-60a7-11e9-954d-46c54544a5d9.png)

**Comment by Ambradibi** [comment]
so in this case you would like the breadcrumb Datasets> Experiments? if one wants to go back to the datasets or cancel the search or click on datasets, no?

the search is implemented also in other pages so in all there would be the breadcrumbs

**Comment by cbotsikas** [comment]
The search page should be routable. This means that the search shouldn't be part of the datasets page and controller.
The breadcrumb for search should be "project name" > Search
