### ISSUE TITLE
Search result popup not shown correctly

### ISSUE THREAD

**Issue by cbotsikas** [aegisbigdata/documentation#138]

**Comment by cbotsikas** [comment]
![image](https://user-images.githubusercontent.com/1640100/56194977-4bee8700-6034-11e9-9a75-61b479a924e2.png)

**Comment by Ambradibi** [comment]
I see it right and I haven't changed anything
![Schermata 2019-04-16 alle 16 42 24](https://user-images.githubusercontent.com/47423916/56219240-b02a3e80-6066-11e9-921a-6b667945acf7.png)

**Comment by cbotsikas** [comment]
Check with chrome too. The problem is that the `.card-body` is expanding to the full window height.
I can see that `.card-body` has `height: 100%` when the parent `.card-item-content` has `display: flex` with `max-height: none`. I'm not sure if that is valid and if the correct behavior is on Chrome or Firefox.

I don't really see what's the benefit on using flexbox in this case. Is it needed somewhere else in the platform?

**Comment by Ambradibi** [comment]
the flex display is for the search boxes. I put height: auto, can you check on chrome too?

**Comment by cbotsikas** [comment]
Yes, `height: auto` fixes behaviour in chrome.
Which search boxes? 
I still find this solution over-complicated for no apparent reasons. Removing all flex related css, gives the same visual result. Am I missing something?
