### ISSUE TITLE
Login help pages need styling

### ISSUE THREAD

**Issue by cbotsikas** [aegisbigdata/documentation#145]
Derived from the outdated https://github.com/aegisbigdata/documentation/issues/8

**Comment by Ambradibi** [comment]
I noticed that the 'login help' link works on bbc6 and not on localhost. Why? You know?

**Comment by cbotsikas** [comment]
It's because it's not part of aegis-web module but [hopsworks-admin](https://github.com/aegisbigdata/hopsworks/tree/dev/hopsworks-admin/src/main/webapp)
We could fix localhost development to proxy the bbc6 pages, but i think it's not gonna help you more than just viewing the pages directly at bbc6.
This module is using Java PrimeFaces, so it's not going to work with grunt serve like we do for the aegis-web module.

**Comment by Ambradibi** [comment]
so how do I view it in localhost to modify the frontend?
