### ISSUE TITLE
Files Page - fix top bar

### ISSUE THREAD

**Issue by Ambradibi** [aegisbigdata/documentation#148]
![image (2)](https://user-images.githubusercontent.com/47423916/56590326-34d90780-65e7-11e9-85c3-0627372c67a1.png)

**Comment by FabiApfelkern** [comment]
@Ambradibi Can you create a pull request for this?

**Comment by Ambradibi** [comment]
already done and merged. You can delete this issue

**Comment by FabiApfelkern** [comment]
Are you sure? I have the latest version on my machine and it looks like this: 
![grafik](https://user-images.githubusercontent.com/1488424/57078296-48bef080-6cee-11e9-8861-f66a26929c86.png)

**Comment by Ambradibi** [comment]
@FabiApfelkern https://github.com/aegisbigdata/hopsworks/pull/32#pullrequestreview-230086619

**Comment by FabiApfelkern** [comment]
@cbotsikas Do you have this in the current dev branch?

**Comment by FabiApfelkern** [comment]
I clearified it.
