### ISSUE TITLE
Add Dataset Button not working

### ISSUE THREAD

**Issue by FabiApfelkern** [aegisbigdata/documentation#149]
This button is not working for me: 

![grafik](https://user-images.githubusercontent.com/1488424/56722428-59e48c00-6747-11e9-910f-794e254ec8dd.png)

**Comment by Ambradibi** [comment]
@FabiApfelkern @cbotsikas in the datasets.html file on line 139 `<div class="file-box file-box-height" ng-click="datasetsCtrl.newDataSetModal()">` the 's' of 'DataSet' must be uppercase and not lowercase. So it works! 
If you already have an open branch, can you make this change please?

**Comment by cbotsikas** [comment]
duplicate and fixed with https://github.com/aegisbigdata/documentation/issues/177
