### ISSUE TITLE
Support for opening multiple files in the Visualizer

### ISSUE THREAD

**Issue by pitsios-s** [aegisbigdata/documentation#156]

**Comment by pitsios-s** [comment]
This is partially supported in the sense that a user can open file X, create a chart and add it to the dashboard. Then, he/she can open file Y, create a new chart and add it to the dashboard and so on.

On the other hand, allowing the visualizer to open multiple files simultaneously and creating charts that may result from combinations of those datasets (i.e joining) is a very bad idea. The reason is that the Visualizer notebook works only the local kernel, which has very limited resources compared to the Spark kernel. Thus, any kind of heavy operations such as dataset joining or keeping in-memory multiple datasets could result in unexpected behavior.

So, in such cases where combination of multiple files is required, it would be better to merge the datasets or apply any filters in the QB, and then use the produced result in the visualizer.

**Comment by cbotsikas** [comment]
I think during the Graz meeting your first paragraph scenario was in mind. 
The proposal was similar to "It would be nice to select multiple files so that the user can go in and create the charts for each file and add them to the dashboard sequentially."

**Comment by pitsios-s** [comment]
So, in a sense, what was discussed is already supported, correct?

**Comment by cbotsikas** [comment]
Yes, what is missing is to be able to  select multiple files in datasets and "right click -> open in visualiser". Then of course the visualiser should be able to handle the passed arguments and allow the user to sequentially make the charts without the need of selecting the files to open

**Comment by cbotsikas** [comment]
It's more like an extension to https://github.com/aegisbigdata/documentation/issues/103 task

**Comment by pitsios-s** [comment]
I see, I wasn't aware that we were talking about the right-click functionality. I though that we were referring to the possibility of opening multiple files simultaneously when you are inside the visualizer.

Still, for the right-click functionality I don't think it is a good idea to select multiple files at once for the visualizer. Only one at a time. The reason is mainly because you can't possibly know when the user finishes with the current dataset (he/she may choose more than one chart) unless he/she explicitly chooses to proceed with the next one. Something like this would break the current workflow logic of the general Visualizer.

Right click functionality could be used for one file, but my main objection regards the multiple file support.

**Comment by kperakis** [comment]
I think that the selection of multiple files and the sequential opening of these files in the visualizer, is at this point an overkill. I don't think there was ever any such actual requirement, and especially not by the demonstrator partners, whole requests have all been met. We should focus on closing more important issues at this point.
