### ISSUE TITLE
Create an LinDA API that returns the EU-controlled - Languages Vocabulary first

### ISSUE THREAD

**Issue by smouzakitis** [aegisbigdata/documentation#173]
https://publications.europa.eu/en/web/eu-vocabularies/authority-tables

**Comment by FabiApfelkern** [comment]
We will need the following vocabulary at least:

https://publications.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/language
https://publications.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/licence
https://publications.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/data-theme
https://publications.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/file-type
https://publications.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/access-right

**Comment by FabiApfelkern** [comment]
It will be also good if the multilinguality already provided be these vovabularies can be integrated.

**Comment by cbotsikas** [comment]
Duplicate to https://github.com/aegisbigdata/documentation/issues/118
