### ISSUE TITLE
Files page: Details tabs issue

### ISSUE THREAD

**Issue by mmeglio** [aegisbigdata/documentation#183]
Details tabs, text doesn’t make sense and has styling issue (overlap).

**Comment by Ambradibi** [comment]
@cbotsikas What does it overlap? I see it correct. Can you send me a screenshot? 
And what information would you like to see?

**Comment by cbotsikas** [comment]
I'm not sure, maybe @mmeglio can provide more info

**Comment by mmeglio** [comment]
Hi, I've had a look but was not able to re-create the overlap problem.. unless it was meant the following:

![image](https://user-images.githubusercontent.com/32269800/58634952-e48f4c80-82ec-11e9-87e7-fb36f42bcf53.png)

with the right column covering the central frame of the page. But this happens of course because the web site is not responsive..

**Comment by Ambradibi** [comment]
![Schermata 2019-06-10 alle 11 33 30 AM](https://user-images.githubusercontent.com/47423916/59186937-782a0e00-8b74-11e9-9e55-b7b5f7a6e772.png)

compared to the information to be displayed, these are related to the file. Which make sense to print?

**Comment by cbotsikas** [comment]
Seems to be outdated/fixed
![image](https://user-images.githubusercontent.com/1640100/61093112-3d541800-a449-11e9-8c2c-0e56b7bc009f.png)
