### ISSUE TITLE
Files page: wrong breadcrumb 

### ISSUE THREAD

**Issue by mmeglio** [aegisbigdata/documentation#184]
The breadcrumb is wrong.

**Comment by Ambradibi** [comment]
@cbotsikas @FabiApfelkern 
what do you mean? what should be the correct one? instead of _datasets_ there must be the _name of the project_?
![Schermata 2019-05-30 alle 11 51 39 AM](https://user-images.githubusercontent.com/47423916/58624774-5063bc00-82d1-11e9-81e3-874cee4418df.png)

**Comment by cbotsikas** [comment]
@Ambradibi yes Ambra, it should have included the project name too, like: demo_kafka_admin0… > DataSets > TestJob
Don't sweat too much on this issue, the action bar will change again soon as discussed in Graz meeting https://github.com/aegisbigdata/documentation/issues/164
