### ISSUE TITLE
Members: it doesn't work!

### ISSUE THREAD

**Issue by mmeglio** [aegisbigdata/documentation#188]
It doesn’t work -> if had select box instead of text box.

![image](https://user-images.githubusercontent.com/32269800/57700729-d7226300-765a-11e9-9fb3-89e2db15c12f.png)

**Comment by cbotsikas** [comment]
@Ambradibi this is still an open issue, the select member list is empty. Please use also [Hopsworks UI](https://bbc6.sics.se:8181/hopsworks/#!/) for comparison and check [the code too](https://github.com/aegisbigdata/hopsworks/tree/dev/hopsworks-web/yo)
