### ISSUE TITLE
Cross-lingual Capabilities at semantic / data level

### ISSUE THREAD

**Issue by smouzakitis** [aegisbigdata/documentation#19]
I think the reviewers want to see something more than the translation of the user interface - based on the DoA, so this is a different issue than #18 

We need to cover cross-lingual capabilities at a semantic /data level, such as cross-lingual semantic search and data query

**Comment by YuriGlickman** [comment]
Any ideas how can we do it?

**Comment by FabiApfelkern** [comment]
RDF has this feature by default. We will add it to the metadata service Related to #22
