### ISSUE TITLE
Open with AEGIS tools from the context menu, upon right click files

### ISSUE THREAD

**Issue by cbotsikas** [aegisbigdata/documentation#195]
The user should be able to right click on files from Datasets page and open them directly in any of the AEGIS tools. 
- [x] Support Query builder
- [x] Support Visualizer
- [ ] Support AEC

It would be nice to also work when selecting multiple files.

**Comment by cbotsikas** [comment]
This is related to https://github.com/aegisbigdata/documentation/issues/103 https://github.com/aegisbigdata/documentation/issues/156 https://github.com/aegisbigdata/documentation/issues/86

**Comment by pitsios-s** [comment]
@cbotsikas Isn't this issue also related to #28 and #33 ?

**Comment by cbotsikas** [comment]
yes but not duplicates
