### ISSUE TITLE
Notebook contextual menu within Datasets/Files view

### ISSUE THREAD

**Issue by o-alex** [aegisbigdata/documentation#202]
If I go to a notebook through the Datasets/Files view, I get the following behaviour:
1. notebook is not selected - if I right click I get a contextual menu that has option to open notebook in Jupyter (this is the expected behaviour)
2. if I select the file/notebook - if I right click, the contextual menu I get now does not have the option to open notebook in Jupyter

**Comment by Ambradibi** [comment]
@o-alex how do I access on a notebook through the Dataset/Files view? Can you send screenshots please?

**Comment by o-alex** [comment]
1. Here I have the option to open notebook in Jupyter:
<img width="1440" alt="Screenshot 2019-06-06 at 15 09 37" src="https://user-images.githubusercontent.com/5680636/59035272-34ca5980-886d-11e9-8c05-c569834dfa1a.png">
2. Here I don't have the option anymore:
<img width="1440" alt="Screenshot 2019-06-06 at 15 09 42" src="https://user-images.githubusercontent.com/5680636/59035288-401d8500-886d-11e9-8263-78b72f2838ca.png">

**Comment by Ambradibi** [comment]
@o-alex understood, thanks. I'll fix it right away
