### ISSUE TITLE
Dataset Box not clickable

### ISSUE THREAD

**Issue by FabiApfelkern** [aegisbigdata/documentation#4]
On the landing page the dataset boxes are not linking to anything although the cursor is changing to a hand. Even the datasets of the logged in user are not clickable. In general the available actions should be very clear. The context menu is also very small and easy to overlook. 

![grafik](https://user-images.githubusercontent.com/1488424/43519809-1f280e94-9591-11e8-9893-1da524c2bab6.png)

**Comment by mmeglio** [comment]
The behavior is inherited from Hopsworks. We'll remove the cursor changing to a hand. We can enlarge the hamburger icon

**Comment by AleCalcagno** [comment]
Fixed (to be deployed on the TESTBED)

**Comment by FabiApfelkern** [comment]
Please leave it open. It doesn't matter where the bahavior originates from. :)
