### ISSUE TITLE
Search result view broken

### ISSUE THREAD

**Issue by FabiApfelkern** [aegisbigdata/documentation#5]
The result view of the search has several issues:

* The filter box is hidden behind the menu bar
* The results are left aligned
* The boxes are not clickable
* Can this inline scrolling be avoided?
* Same issuses as here #3 

![grafik](https://user-images.githubusercontent.com/1488424/43520000-b793e662-9591-11e8-8017-b35f701a9142.png)

**Comment by mmeglio** [comment]
•The filter box is hidden behind the menu bar **BUG when the search is used from the Home page – TO BE FIXED**
•The results are left aligned
•The boxes are not clickable
•Can this inline scrolling be avoided?

**Comment by AleCalcagno** [comment]
Fixed (to be deployed on the TESTBED)
