### ISSUE TITLE
Click options in project view confusing

### ISSUE THREAD

**Issue by FabiApfelkern** [aegisbigdata/documentation#6]
The boxes behave unexpected. They have the following options:

* See details on the right sidebar by clicking on the grey area
* Context menu by clicking on the hamburger icon
* There is NO direct way to access the files

Better would be (a suggestion):

* Context menu with right click
* Go to files with right click
* Details with a distinct button

![grafik](https://user-images.githubusercontent.com/1488424/43520137-30cf0ed0-9592-11e8-82de-90bdf7582eac.png)

**Comment by mmeglio** [comment]
Actually there is a direct way to access the files, i.e. clicking on the title in the blue bar:

![uno](https://user-images.githubusercontent.com/32269800/43574550-00769c4c-9634-11e8-9c8e-3c27078a2016.png)

By the way, to improve the usability, we will change the options of boxes as follows:
•	Hamburger button displays the context menu (left-click)
•	Left-click in the grey area: enter the dataset
•	Right-click in the grey area displays the details on the right bar.

**Comment by mmeglio** [comment]
We changed the logic behind the interaction with the datasets, due to some issues in the developments, as follows:
-	left-click in the grey area -> enter the dataset ( browse files)
-	left-click in the top blue bar -> displays the details on the right bar
-	right-click everywhere -> displays the context menu

**Comment by FabiApfelkern** [comment]
cool! is that available online?

**Comment by AleCalcagno** [comment]
Fixed (to be deployed on the TESTBED)
