### ISSUE TITLE
Concept for Integration of Notebook-Scripts

### ISSUE THREAD

**Issue by FabiApfelkern** [aegisbigdata/documentation#67]
Public project for hosting scripts
AEGIS user
Versioning
Creation of new project
Pre-defined scripts in Notebook folder
Only the latest
Popup for importing pre-defined scripts
Open Jupyter from context menu

**Comment by FabiApfelkern** [comment]
@o-alex Any updates here?

**Comment by cbotsikas** [comment]
Implemented via other issues:
https://github.com/aegisbigdata/documentation/issues/85
https://github.com/aegisbigdata/documentation/issues/86
https://github.com/aegisbigdata/documentation/issues/28
