### ISSUE TITLE
Check Frontend regarding I18N

### ISSUE THREAD

**Issue by FabiApfelkern** [aegisbigdata/documentation#69]

**Comment by FabiApfelkern** [comment]
We built a small prototype for this: http://bbc6.sics.se:8080/fokus/#!/
You can switch languages in the header. The implementation is quite easy with https://angular-translate.github.io/
But we need to add to every string in the frontend a filter:
```
<span>New Project</span> zu <span>{{'New Project' | translate}}</span>. 
```
Do we want to do that?

**Comment by smouzakitis** [comment]
My opinion and according to what we discussed, it is good but i think this is low priority compared to other tasks.

**Comment by smouzakitis** [comment]
My opinion and according to what we discussed, it is good but i think this is low priority compared to other tasks.

**Comment by smouzakitis** [comment]
My opinion and according to what we discussed, it is good but i think this is low priority compared to other tasks.

**Comment by FabiApfelkern** [comment]
Done. Now it has to applied. #18
