### ISSUE TITLE
Project name is unique across the hops instance

### ISSUE THREAD

**Issue by cbotsikas** [aegisbigdata/documentation#93]
Is it possible to have the project names unique for the user instead of all hops projects? What is the current scope?

![image](https://user-images.githubusercontent.com/1640100/48252764-cff96e80-e405-11e8-84bf-3e10bf8f58fa.png)

**Comment by jimdowling** [comment]
They are global scope. Because a project is a subtree in HDFS, rooted under /Projects/<project_name>
It's a huge change to modify this. They are like github repos - globally unique.

**Comment by cbotsikas** [comment]
ah, ok. Thank you for clarifying that @jimdowling. I thought it was similar to the hdfs user, <project_name>__<project_user> or similar.
