### ISSUE TITLE
Contact the people responsible for the front-end to get info about the front-end stack / framework they use:

### ISSUE THREAD

**Issue by smouzakitis** [aegisbigdata/documentation#96]
Contact the people responsible for the front-end to get info about the front-end stack / framework they use:
-Admin bootstrap theme or any other original theme / front-end framework they used for hopsworks (if any)
-Any potential styles generation  files (like .less)
**Deadline 14/12/2018**

**Comment by o-alex** [comment]
We are using JSF and primefaces. We will soon replace it with angular7.

**Comment by cbotsikas** [comment]
@o-alex are the current css files located at https://github.com/aegisbigdata/hopsworks/tree/aegis/hopsworks-web/yo/app/styles are generated/modified by hand or you have a mechanism to gererate them via primefaces?

**Comment by o-alex** [comment]
the files are generated by hand

**Comment by FabiApfelkern** [comment]
@smouzakitis Is this still an issue?

**Comment by cbotsikas** [comment]
No, nothing to do here.
