### ISSUE TITLE
Discuss with front-end designer for the plan for a nice UI mockups / html(if possible)  (2-3 mockups - graphics, color, layout)

### ISSUE THREAD

**Issue by smouzakitis** [aegisbigdata/documentation#97]
Discuss with front-end designer for the plan for a nice UI mockups / html(if possible)  (2-3 mockups - graphics, color, layout)
Deadline 14/12/2018

**Comment by FabiApfelkern** [comment]
It's discussed and @michaelalemu will work on some designs. @michaelalemu Feel free to post any questions and intermediate results here.
